import logging
import time
import discord
import difflib
import re
from collections import Counter, deque

logger = logging.getLogger(__name__)

class GuildContext:
    def __init__(self):
        self.game_name: str | None = None
        self.game_start_ts: float = 0.0
        self.active_users: set[int] = set()
        self.last_update: float = 0.0
        # Rolling buffer for bot's recent output phrases (text, timestamp)
        self.echo_buffer: deque[tuple[str, float]] = deque(maxlen=50)

class ContextManager:
    def __init__(self, bot):
        self.bot = bot
        self._guilds: dict[int, GuildContext] = {}

    def get_context(self, guild_id: int) -> GuildContext:
        if guild_id not in self._guilds:
            self._guilds[guild_id] = GuildContext()
        return self._guilds[guild_id]

    def add_bot_output(self, guild_id: int, text: str):
        """
        Registers text generated by bot to ignore it if users read it back.
        Splits text into sentences for better granularity.
        """
        ctx = self.get_context(guild_id)
        now = time.time()
        
        # Split by sentence endings (. ! ?)
        sentences = re.split(r'[.!?\n]+', text)
        for s in sentences:
            clean = self._normalize_text(s)
            if len(clean) > 10: # Only meaningful phrases
                ctx.echo_buffer.append((clean, now))
        
        logger.info(f"Added {len(sentences)} sentences to echo buffer for Guild {guild_id}")

    def is_echo(self, guild_id: int, user_text: str, threshold: float = 0.65) -> bool:
        """
        Checks if user_text is too similar to something the bot recently wrote.
        """
        ctx = self.get_context(guild_id)
        if not ctx.echo_buffer:
            return False
            
        norm_user = self._normalize_text(user_text)
        if len(norm_user) < 5: return False # Too short to judge

        now = time.time()
        # Cleanup old buffer (older than 20 mins)
        while ctx.echo_buffer and (now - ctx.echo_buffer[0][1] > 1200):
            ctx.echo_buffer.popleft()

        for (bot_text, _) in ctx.echo_buffer:
            # Quick length check optimization
            if abs(len(bot_text) - len(norm_user)) > len(bot_text) * 0.5:
                continue

            # Fuzzy Match
            ratio = difflib.SequenceMatcher(None, bot_text, norm_user).ratio()
            if ratio >= threshold:
                logger.info(f"Echo detected ({int(ratio*100)}%): '{user_text}' ~= '{bot_text[:20]}...'")
                return True
                
        return False

    def _normalize_text(self, text: str) -> str:
        # Lowercase, remove punctuation/symbols
        text = text.lower()
        return re.sub(r'[^a-zа-я0-9\s]', '', text).strip()

    async def update_presence(self, guild: discord.Guild, voice_channel: discord.VoiceChannel):
        """
        Scans users in the voice channel and determines the 'dominant' game.
        """
        ctx = self.get_context(guild.id)
        
        games = []
        active_ids = set()
        
        for member in voice_channel.members:
            if member.bot: continue
            active_ids.add(member.id)
            
            if not member.activities: continue
            
            for act in member.activities:
                if act.type == discord.ActivityType.playing:
                    games.append(act.name)
        
        ctx.active_users = active_ids
        ctx.last_update = time.time()

        if not games:
            # No games detected, maybe keep old context if recent?
            # For now, clear it if silence matches logic
            if time.time() - ctx.last_update > 300: # 5 mins
                ctx.game_name = None
            return

        # Majority Vote
        counts = Counter(games)
        most_common, count = counts.most_common(1)[0]
        
        # If at least 30% of people (or >1 person) are playing it
        threshold = max(1, len(active_ids) * 0.3)
        if count >= threshold:
            if ctx.game_name != most_common:
                ctx.game_name = most_common
                ctx.game_start_ts = time.time()
                logger.info(f"Context switch for {guild.name}: {ctx.game_name}")
        
    def get_ai_context_string(self, guild_id: int) -> str:
        ctx = self.get_context(guild_id)
        if not ctx.game_name:
            return "Контекст: Просто общение / Игра не определена."
        
        duration_mins = int((time.time() - ctx.game_start_ts) / 60)
        return f"Контекст: Группа играет в '{ctx.game_name}' уже {duration_mins} минут. Учитывай сленг этой игры."

